### ISSUE TITLE
Support for history points and/or time series extraction

### ISSUE THREAD

**Issue by vbaconnet** [ExtremeFLOW/neko#827]
It would be great if we had some kind of "history points" (which we will call `probes`) like in Nek5000, or more generally a way to extract time series, in-situ, of `u,v,w,p` at a single point (or a series of points). 

This is how I understand the process to be:
1. Read a list of `x,y,z` coordinates from a text input file.
2. Perform a global point-search in the mesh to find which elements own which points (octree structure already available in Neko, see #577)
3. Using `x,y,z` and element ids (or other relevant parameter) as input, perform a local mapping to `r,s,t` coordinates.
4. Interpolate `u,v,w,p` (or custom list of) fields, and
5. Output the interpolated fields to a file, either appended to the input file or to a separate file.

## Checklist

A very simple first draft of a checklist, suggestions on how to break these down into more specific tasks are welcome: 

- [x] Create a file type for reading floating-point input data (Done #898)
- [x] Support for global search of a point in the mesh
- [x] Support for local mapping from `x,y,z` to `r,s,t`
- [x] Integration of field interpolation (Done #900)
- [x] Support for writing floating-point data to a text file (Done #898)

## Possible future improvements

- Similar to statistics, `probes_write_control` and `probes_write_par`
- Possibility to select which fields to interpolate (could be nicely done with the JSON stuff?)

## How it works on Nek5000

1. The points to read are specified in a single file:

```f90
3           ! Number of points to read
0.5 0.1 0.1 ! x y z for pt1
0.2 0.1 0.2 ! x y z for pt2
0.0 0.2 0.1 ! x y z for pt3  
```

2. In the user file, one can call the `hpts` subroutine to append the fields `u,v,w,p` evaluated at each of the points, to the above file. For example, writing data every 10 time steps would be done like this:

```f90
! usrcheck, this is called at the end of every time step
  subroutine user_check(t, tstep,u, v, w, p, coef, param)
    real(kind=rp), intent(in) :: t
    integer, intent(in) :: tstep
    type(coef_t), intent(inout) :: coef
    type(field_t), intent(inout) :: u
    type(field_t), intent(inout) :: v
    type(field_t), intent(inout) :: w
    type(field_t), intent(inout) :: p
    type(param_t), intent(inout) :: param

    ! Call history points every 10 time steps
    if ( mod(tstep,10) .eq. 0 ) call hpts() ! or maybe hpts(t,u,v,w,p)

  end subroutine user_check
```

In the history points file, after 10 iterations, we should get something like:
```f90
3           ! Number of points to read
0.5 0.1 0.1 ! x y z for pt1
0.2 0.1 0.2 ! x y z for pt2
0.0 0.2 0.1 ! x y z for pt3  
2.0000000E-03  9.9316318E-01  1.8013885E-02  2.8209461E-02  0.0000000E+00 ! t,u,v,w,p at pt1 at iteration 10
2.0000000E-03  9.8799883E-01  1.7938701E-02  2.1289890E-02  0.0000000E+00 ! t,u,v,w,p at pt2 at iteration 10
2.0000000E-03  9.8375951E-01  2.1394064E-02  1.9778667E-02  0.0000000E+00 ! t,u,v,w,p at pt3 at iteration 10
```

**Comment by njansson** [comment]
> 
> - [ ] Support for fast-search of a point in the mesh (using octree?) 
> 
`src/mesh/octree.f90` can probably be used as a building block. Create an octree out of the bounding boxes of the elements, some will overlap so a search must be able to return a set of boxes, for which a more exact search is needed, eg distance surface or centroid.

**Comment by MartinKarp** [comment]
I think for a start, maybe looking at non-deformed elements is good. If we have that working nicely (the structure and so on) for when we know the coordinates in r-s-t coords, I think adding support for curved then should be a matter of adding some extra logic for the bounding boxes and so on as you say Niclas.

**Comment by timofeymukha** [comment]
I think some of the stuff in the check list can be ticked, or? How are we doing here in general, I recall that we decided to integrate the nek5000 stuff for element search, or?

**Comment by njansson** [comment]
> I think some of the stuff in the check list can be ticked, or? How are we doing here in general, I recall that we decided to integrate the nek5000 stuff for element search, or?

Yes, integrate in the sense that rely on an external lib (gslib) for element searching etc.

**Comment by vbaconnet** [comment]
Yes I was actually going to take some time to reorganize the check list a little bit. I guess at this point we have input/output with the `csv_file` module as well as the interpolation routines. 

At the moment, as Niclas said, the mapping and point searching can be offloaded to gslib which I am trying out right now and seems to work for the most part.

Additionally I am slowly writing a `probes` module (in the `feature/probes`) branch to encapsulate all of this but kind of put on hold for now :)
