### ISSUE TITLE
JSON case file roadmap

### ISSUE THREAD

**Issue by timofeymukha** [ExtremeFLOW/neko#831]
Let's use this as a metaissue to track the progress towards a JSON parfile.

- [x] Add [the JSON library](https://github.com/jacobwilliams/json-fortran) to the build.
- [x] Resolve issues with `json-fortran` compilation with all necessary compilers.
- [x] Develop the JSON scheme for the case file. 
- [x] Add JSON-based `case_t` class. At least partially done [here](https://github.com/ExtremeFLOW/neko/blob/develop/contrib/pyneko/src/json_case.f90).
- [x] Fix all examples.
- [x] #891

**Comment by timofeymukha** [comment]
@njansson If I remember correctly, introducing the JSON library somehow forced a change to using Neko as a .so instead of a static library? Or am I confusing things with Python... In any case, I fear that you will have to be assigned to the first task, unless @MartinKarp feels up to it. I still use the build system as a monkey, more or less.

**Comment by njansson** [comment]
> @njansson If I remember correctly, introducing the JSON library somehow forced a change to using Neko as a .so instead of a static library? Or am I confusing things with Python... In any case, I fear that you will have to be assigned to the first task, unless @MartinKarp feels up to it. I still use the build system as a monkey, more or less.

No it will not force `libneko` to be a `.so` file instead, that was due to Python.

Adding the JSON library to `configure.ac` is as simple as

```
PKG_CHECK_MODULES([JSON_Fortran],[json-fortran >= 8.3.0])
LIBS="$JSON_Fortran_LIBS $LIBS"
FCFLAGS="$JSON_Fortran_CFLAGS $FCFLAGS"
```

**Comment by njansson** [comment]
> But the above would rely on one already having installed `json-fortran` in a way that `pkg-config` finds it, right?
> 
> I guess the question is how we want to approach this, since `json-fortran` will be a hard dependency. Should building it be incorporated directly in Neko's build? Or should we maybe have a `thirdparty` directory with important deps as git submodules and associated build scripts?

I would strongly argue against having it as part of Neko's build, or in a `thirdparty` directory. Either of these is a recipe for disaster I would say.

**Comment by timofeymukha** [comment]
Regarding part of Neko's build I agree. With the `thirdparty` I don't necessary see a disaster if one just groups git submodules there for, e.g. pfunit, json-fortran, etc. I would argue that BLAS/LAPACK are a bit special since they are almost always installed centrally on the system by the vendors, or just via `apt-get` locally. They are kind of the same category as MPI. But I guess for now it is not so important.
